### ISSUE TITLE
missing documentation

### ISSUE THREAD

**Issue by lpatiny** [mljs/airpls#1]
Please add jsDoc in the code and run `cheminfo docs` to update the documentation.

Please also provide a correct README.

**Comment by jobo322** [comment]
Documentation for the exported function was done and the README was updated on this [commit](https://github.com/mljs/airPLS/commit/15760af80f98052e37e22c491ee0e05fe5dd48ef), but I'm having error when I ran `cheminfo docs`, @lpatiny is it necessary to install something else?

**Comment by lpatiny** [comment]
Did you install cheminfo-tools ?

`npm i --global cheminfo-tools`

Could you give me the error ?

**Comment by jobo322** [comment]
yes, I did it before, apparently was a rights problem

**Comment by jobo322** [comment]
It is fixed
