### ISSUE TITLE
How to deal correctly with eslint

### ISSUE THREAD

**Issue by lpatiny** [mljs/airpls#2]
In our cheminfo eslint preferences we import 2 plugins as peer dependencies and dev dependencies:

https://github.com/cheminfo/eslint-config/blob/c4cdac80b9e621605bd8e4f03fb8a27c4bdb5e8d/package.json#L23-L27

Nevertheless when I use our eslint preferences in this project without explicitly import the 2 plugins:
* eslint-plugin-import
* eslint-plugin-jest

I have an `eslint` error for those 2 missing plugins.

So the only way was to add the plugins

https://github.com/mljs/airPLS/blob/485b1aa2e4cc3f79d930c176cc1d8ecfeee39670/package.json#L41-L45

Is this normal ?

**Comment by targos** [comment]
Yes. You need to install peer dependencies yourself. Look at the config's readme to see how it can be done automatically

**Comment by lpatiny** [comment]
And what is the reason why it is a peer-dependency and not simply a dependency ?

**Comment by targos** [comment]
Because it doesn't work as a dependency. That's how all eslint configs are setup
